apiVersion: apps/v1
kind: Deployment
metadata:
  name: basicapi-v1
  labels:
    app: basicapi
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: basicapi
      version: v1
  template:
    metadata:
      labels:
        app: basicapi
        version: v1
    spec:
      containers:
        - name: basicapi
          image: srghouse/basic-rest-api:1.0
          imagePullPolicy: IfNotPresent #Always
          ports:
            - containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: basicapiservice
  labels:
    app: basicapi
    service: basicapi
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30080
  selector:
    app: basicapi