name: Build-deploy-api
on:
  push:
    branches: 
      - main
      - master
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:
    
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: run tests
        run: |
          pwd
          ls
          mvn -B clean test
  package:
    runs-on: ubuntu-latest
    needs: [build-test]
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: create package
        run: mvn -B package -Dskiptests
      - name: upload package
        uses: actions/upload-artifact@v3
        with:
          name: api-jar
          path: target
      - name: info jar
        run: |
          ls
          ls target
  publish:
    runs-on: ubuntu-latest
    needs: [package]
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: download-artifact
        uses: actions/download-artifact@v3
        with:
          name: api-jar
          path: target
      - name: info jar
        run: |
          ls -l
          ls target
      - name: docker-login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: srghouse/myapi:latest
